"""
Email the latest Kobo 99 weekly book list generated by scraper/scrape.py.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import smtplib
from email.message import EmailMessage
from pathlib import Path


EMAIL_SPLIT_RE = re.compile(r"[,;\s]+")


def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def _env_int(name: str, default: int) -> int:
    value = _env(name)
    return int(value) if value else default


def parse_recipients(raw: str) -> list[str]:
    recipients = [item.strip() for item in EMAIL_SPLIT_RE.split(raw) if item.strip()]
    invalid = [addr for addr in recipients if "@" not in addr or addr.startswith("@") or addr.endswith("@")]
    if invalid:
        raise ValueError(f"Invalid recipient address(es): {', '.join(invalid)}")
    if not recipients:
        raise ValueError("At least one recipient is required.")
    return recipients


def load_latest(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _rating(book: dict) -> str:
    score = book.get("avg_score")
    return f"{score:.2f}" if isinstance(score, int | float) else "-"


def build_plain_text(data: dict) -> str:
    lines = [
        f"Kobo 99 書單：{data.get('year')}-W{int(data.get('week', 0)):02d}",
        str(data.get("sale_label", "")).strip(),
        str(data.get("kobo_url", "")).strip(),
        "",
    ]
    for idx, book in enumerate(data.get("books", []), 1):
        lines.extend(
            [
                f"{idx}. {book.get('title', '')}",
                f"   作者：{book.get('author') or '-'}",
                f"   綜合評分：{_rating(book)}",
                f"   Kobo：{book.get('kobo_url') or '-'}",
                "",
            ]
        )
    return "\n".join(lines).strip() + "\n"


def build_html(data: dict) -> str:
    year = html.escape(str(data.get("year", "")))
    week = int(data.get("week", 0))
    sale_label = html.escape(str(data.get("sale_label", "")))
    kobo_url = html.escape(str(data.get("kobo_url", "")), quote=True)

    rows = []
    for idx, book in enumerate(data.get("books", []), 1):
        title = html.escape(str(book.get("title", "")))
        author = html.escape(str(book.get("author") or "-"))
        rating = html.escape(_rating(book))
        url = html.escape(str(book.get("kobo_url") or ""), quote=True)
        rows.append(
            "<tr>"
            f"<td style=\"padding:8px;border-bottom:1px solid #ddd;vertical-align:top;\">{idx}</td>"
            f"<td style=\"padding:8px;border-bottom:1px solid #ddd;vertical-align:top;\"><a href=\"{url}\">{title}</a></td>"
            f"<td style=\"padding:8px;border-bottom:1px solid #ddd;vertical-align:top;\">{author}</td>"
            f"<td style=\"padding:8px;border-bottom:1px solid #ddd;vertical-align:top;text-align:right;\">{rating}</td>"
            "</tr>"
        )

    return f"""\
<!doctype html>
<html>
  <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;line-height:1.5;">
    <h1 style="font-size:20px;margin:0 0 8px;">Kobo 99 書單：{year}-W{week:02d}</h1>
    <p style="margin:0 0 12px;">{sale_label}</p>
    <p style="margin:0 0 16px;"><a href="{kobo_url}">Kobo 官方書單</a></p>
    <table style="border-collapse:collapse;width:100%;max-width:960px;">
      <thead>
        <tr>
          <th align="left" style="padding:8px;border-bottom:2px solid #333;">#</th>
          <th align="left" style="padding:8px;border-bottom:2px solid #333;">書名</th>
          <th align="left" style="padding:8px;border-bottom:2px solid #333;">作者</th>
          <th align="right" style="padding:8px;border-bottom:2px solid #333;">綜合評分</th>
        </tr>
      </thead>
      <tbody>
        {''.join(rows)}
      </tbody>
    </table>
  </body>
</html>
"""


def send_email(data: dict, recipients: list[str], args: argparse.Namespace) -> None:
    sender = args.from_addr or args.smtp_user
    if not sender:
        raise ValueError("SMTP_FROM or SMTP_USER is required.")

    subject = f"{args.subject_prefix} {data.get('year')}-W{int(data.get('week', 0)):02d}".strip()
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)
    msg.set_content(build_plain_text(data))
    msg.add_alternative(build_html(data), subtype="html")

    if not args.smtp_host:
        raise ValueError("SMTP_HOST is required.")

    if args.smtp_ssl:
        client: smtplib.SMTP = smtplib.SMTP_SSL(args.smtp_host, args.smtp_port, timeout=30)
    else:
        client = smtplib.SMTP(args.smtp_host, args.smtp_port, timeout=30)

    with client:
        if args.smtp_starttls:
            client.starttls()
        if args.smtp_user or args.smtp_password:
            client.login(args.smtp_user, args.smtp_password)
        client.send_message(msg)


def main() -> None:
    parser = argparse.ArgumentParser(description="Send Kobo 99 weekly book list by email.")
    parser.add_argument("--data", default="docs/data/latest.json", type=Path)
    parser.add_argument("--recipients", default=_env("EMAIL_RECIPIENTS"))
    parser.add_argument("--smtp-host", default=_env("SMTP_HOST"))
    parser.add_argument("--smtp-port", default=_env_int("SMTP_PORT", 587), type=int)
    parser.add_argument("--smtp-user", default=_env("SMTP_USER"))
    parser.add_argument("--smtp-password", default=_env("SMTP_PASSWORD"))
    parser.add_argument("--from-addr", default=_env("SMTP_FROM"))
    parser.add_argument("--subject-prefix", default=_env("EMAIL_SUBJECT_PREFIX", "Kobo 99 書單"))
    parser.add_argument("--smtp-ssl", action="store_true", default=_env("SMTP_SSL").lower() == "true")
    parser.add_argument("--smtp-starttls", action="store_true", default=_env("SMTP_STARTTLS", "true").lower() == "true")
    args = parser.parse_args()

    recipients = parse_recipients(args.recipients)
    data = load_latest(args.data)
    send_email(data, recipients, args)
    print(f"Sent Kobo 99 email to {len(recipients)} recipient(s).")


if __name__ == "__main__":
    main()
